### PR TITLE
{excmds,dom}.ts: Fix external editor updating the wrong field

### LINKED ISSUE #632: External editor can update text in wrong field
If you change Firefox's focus before returning from the editor, Tridactyl will update the wrong field.

You need to be able to use the Native Messenger and open an editor to see this.

1. Go to a page with multiple input fields. A Github issue will do.
2. Focus one field (say the issue field), and open in an external editor (Ctrl-i)
3. Return to Firefox, select another field (e.g. the search field)
4. Return to the editor, and close the document
5. The editor contents will now be in the search field, not the issue field.

Textern handles this by saving an "ID" (just a simple counter) along with the dom node when opening the document, then looking the same ID up on return. See `registerText`, `watchElement` and `setText` here:

https://github.com/jlebon/textern/blob/b251d792a27814a486b0bf2d231caaa9a5d18c9f/webex/content.js

### PR DESCRIPTION
**Pull request by glacambre**
I believe this fixes #632 .

### CODE REVIEW

File: src/excmds.ts [hunk 1]
```diff
@@ -144,8 +144,9 @@ export async function getNativeVersion(): Promise<void> {
  * That said, `bind gs fillinput [Tridactyl](https://addons.mozilla.org/en-US/firefox/addon/tridactyl-vim/) is my favourite add-on` could probably come in handy.
  */
 //#content
-export async function fillinput(...content: string[]) {
-    let inputToFill = DOM.getLastUsedInput()
+export async function fillinput(selector: string, ...content: string[]) {
```
Comment (bovine3dom) [inline src/excmds.ts]: This is a breaking change if anyone used this.

Please document `fillinput NULL content to fill` and mention breaking change in changelog :)

File: src/excmds.ts [hunk 2]
```diff
@@ -177,10 +184,12 @@ export async function getinput() {
...
 //#background
 export async function editor() {
-    let url = new URL((await activeTab()).url)
+    let tab = await activeTab()
+    let selector = await Messaging.messageTab(tab.id, "excmd_content", "getInputSelector", [])
+    let url = new URL(tab.url)
     if (!await Native.nativegate()) return
     const file = (await Native.temp(await getinput(), url.hostname)).content
-    fillinput((await Native.editor(file)).content)
+    Messaging.messageTab(tab.id, "excmd_content", "fillinput", [selector, (await Native.editor(file)).content])
```
Comment (bovine3dom) [inline src/excmds.ts]: Why the roundabout fashion? Does selector get mangled?

Comment (glacambre) [reply src/excmds.ts]: I'm not sure I understand your question. If you're asking why I'm using `Messaging.messageTab` rather than just calling `fillinput()`, it's because `fillinput()` will be called in whatever tab is currently active, which might not be the tab the editor was spawned from.

Comment (bovine3dom) [reply src/excmds.ts]: Ah, good thinking : )
